# Generated by Django 6.0 on 2026-01-05 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientModel',
        ),
    ]
