from typing import Protocol
from uuid import UUID

from domain.entities.address import Address


class AddressRepository(Protocol):
    def __init__(self, db) -> None: ...
    def create(self, address: Address) -> Address: ...
    def get_by_id(self, address_id: UUID) -> Address | None: ...
    def list_by_user(self, user_id: UUID) -> list[Address]: ...
    def list_by_client(self, client_id: UUID) -> list[Address]: ...
    def list_by_company(self, company_id: UUID) -> list[Address]: ...
    def update(self, address: Address) -> Address: ...
    def delete(self, address_id: UUID) -> None: ...
