from typing import Protocol
from uuid import UUID

from domain.entities.asset import Asset


class AssetRepository(Protocol):
    def __init__(self, db) -> None: ...
    def create(self, asset: Asset) -> Asset: ...
    def get_by_id(self, asset_id: UUID, user_id: UUID) -> Asset | None: ...
    def list_by_user(
        self, user_id: UUID, client_id: UUID | None = None
    ) -> list[Asset]: ...
    def update(self, asset: Asset) -> Asset: ...
    def delete(self, asset_id: UUID, user_id: UUID) -> None: ...
    def assign_client(
        self, asset_id: UUID, user_id: UUID, client_id: UUID | None
    ) -> Asset: ...
