from typing import Protocol
from uuid import UUID

from domain.entities.client import Client


class ClientRepository(Protocol):
    def __init__(self, db) -> None: ...
    def create(self, client: Client) -> Client: ...
    def get_by_id(self, client_id: UUID, user_id: UUID) -> Client | None: ...
    def list_by_user(self, user_id: UUID) -> list[Client]: ...
    def update(self, client: Client) -> Client: ...
    def delete(self, client_id: UUID, user_id: UUID) -> None: ...
