from typing import Protocol
from uuid import UUID

from domain.entities.company import Company


class CompanyRepository(Protocol):
    def __init__(self, db) -> None: ...
    def create(self, company: Company) -> Company: ...
    def get_by_id(self, company_id: UUID, user_id: UUID) -> Company | None: ...
    def list_by_user(self, user_id: UUID) -> list[Company]: ...
    def update(self, company: Company) -> Company: ...
    def delete(self, company_id: UUID, user_id: UUID) -> None: ...
    def assign_client(self, company_id: UUID, user_id: UUID, client_id: UUID | None) -> Company: ...
