from typing import Protocol


class PasswordHashing(Protocol):
    def verify_password(self, plain_password: str, hashed_password: str) -> bool: ...
    def get_password_hash(self, password: str) -> str: ...
