from typing import Protocol

from domain.entities.user import User


class UserRepository(Protocol):
    def __init__(self, db) -> None: ...
    def create_user(self, user: User) -> None: ...
    def user_exists(self, email: str) -> bool: ...
    def get_user_by_email(self, email: str) -> User | None: ...
